# Generated by Django 5.2.5 on 2025-08-23 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_buyer_customuser_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_agent',
        ),
    ]
