# Generated by Django 5.2.5 on 2025-08-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('listing_type', models.CharField(choices=[('rent', 'Rent'), ('sell', 'Sell')], max_length=10)),
                ('bedrooms', models.IntegerField()),
                ('size_sq_meters', models.FloatField()),
                ('price', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='property_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
