# Generated by Django 5.2.5 on 2025-08-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
